"""Write docs/SIMULATION.md from sim/out/mission_*.json, turn_study.json and assumptions.json."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'out')
DOC = os.path.join(HERE, '..', 'docs', 'SIMULATION.md')
TITLES = {'C_spin': 'Downy again, but turning by spinning in place instead of arcs',
          'A': 'Main course — pickup → 15° ramp → bridge → ramp down → 4 speed breakers → touchdown',
          'B': 'Same course + 1.5 s radio drop on the bridge while forged and replayed packets are sent',
          'C': 'Downy — 60 mm cube off the 400 mm pole, reverse/forward arc turns, place in the target square'}


def main():
    L = ['# End-to-end simulation — Thenar Walker', '',
         'Generated by `sim/make_sim_report.py`. Physics: MuJoCo 3.14, 1 ms steps. Control: the **real firmware '
         'logic** (`firmware/libraries/ThenarLink`: HMAC packet gate + `tw::Robot` state machine) compiled into '
         '`sim/fw_bridge.exe` and run every 10 ms. The operator (leader-arm angles + joystick) is scripted: it sees '
         'the scene like a person would and only sends what a person could send — nothing bypasses the firmware.', '',
         '| Scenario | Result | Simulated time | Video |', '|---|---|---|---|']
    res = {}
    for sc in ('A', 'B', 'C', 'C_spin'):
        p = os.path.join(OUT, f'mission_{sc}.json')
        if os.path.exists(p):
            r = json.load(open(p)); res[sc] = r
            n_ok = sum(c['pass'] for c in r['checks'])
            L.append(f"| {sc}: {TITLES[sc]} | {'**PASS**' if r['all_pass'] else '**FAIL**'} ({n_ok}/{len(r['checks'])}) | "
                     f"{r['sim_time_s']:.1f} s | [mission_{sc}.mp4](../sim/out/mission_{sc}.mp4) |")
    L.append('')
    for sc, r in res.items():
        L += [f'## Scenario {sc} — {TITLES[sc]}', '', f'![](../sim/out/mission_{sc}_2.png)', '', '| Result | Check | Measured |', '|---|---|---|']
        for c in r['checks']:
            L.append(f"| {'PASS' if c['pass'] else '**FAIL**'} | {c['check']} | {c['detail']} |")
        L += ['', 'Events: ' + '; '.join(f"{e['t']:.1f} s {e['event']}" + (f" = {e['value']}" if 'value' in e else '') for e in r['events']), '']
    ts = os.path.join(OUT, 'turn_study.json')
    if os.path.exists(ts):
        t = json.load(open(ts))
        keys = list(next(iter(t.values())).keys())
        L += ['## Turning study (`sim/turn_study.py`)', '',
              'The robot is almost square (wheelbase 152 mm, track 168 mm), so every turn drags tyres sideways. '
              'With grippy TPU on all four wheels it could only spin above ~55 % power and **arc turns barely '
              'worked (2.8°/s)** — in an arc test it reversed 2 m and turned 26°. Stronger (slower) motors barely '
              'help. Hard PETG tyres at the **front** let the front slide while the TPU rear pushes: spin and arcs '
              'both work, it still climbs the ramp and crosses the speed breakers (scenarios A and B). PETG at the '
              '**rear** was also tried and gets stuck on the breakers.', '',
              '| Variant | ' + ' | '.join(keys) + ' |', '|---|' + '---|' * len(keys)]
        for k, v in t.items():
            L.append(f'| {k} | ' + ' | '.join(str(x) for x in v.values()) + ' |')
        L += ['', 'Firmware: rotation has its own scale (50/75/100 %) and a 35 % breakaway floor '
              '(`TURN_SCALE`, `SPIN_MIN` in `tw_robot.h`). Drive like a car where you can (arcs); spin on the spot '
              'only for small corrections or tight spots.', '']
    a = json.load(open(os.path.join(HERE, 'assumptions.json')))
    L += ['## Model inputs and assumptions', '',
          '* Masses: SolidWorks volumes × PETG/TPU densities + datasheet masses; arm link COM/inertia integrated over '
          'the thenar-arms meshes. Robot 2.37 kg.',
          '* Arm kinematics: thenar-arms `simulation/mujoco/so101.xml` (URDF-validated). Finger contacts: 3 boxes per '
          'finger fitted to the jaw meshes (gap is 4–16 mm tighter than the real jaws — conservative).',
          '* Wheels: Ø140 cylinders; JGA25-370 78:1 torque–speed line (stall 6.2 kg·cm, 77 rpm free) × battery 11.6/12 V.',
          '* Servos: MG996R as stall-limited position servos; firmware slew limit applied first.', '',
          '| Assumption | Value |', '|---|---|']
    for k, v in a.items():
        L.append(f'| {k} | {v} |')
    L += ['', '## What the simulation does not prove', '',
          '* Friction values are assumptions (TPU on plywood, thermocol on PETG). Test the real tyres on the ramp and '
          'the real gripper on a thermocol cube.',
          '* Thermocol is modelled rigid; a real EPS cube dents under ~10 N — squeeze gently (gripper 15–20° on the leader).',
          '* The scripted operator has perfect eyes and a steady hand. Practise the course: the human is the controller.',
          '* Wi-Fi is modelled as packet delivery/loss only (no latency jitter, no interference).']
    open(DOC, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print('wrote', os.path.normpath(DOC))


if __name__ == '__main__':
    main()
