"""Write docs/VERIFICATION.md from the machine-readable evidence in cad/evidence and analysis/."""
import json
import os
import re

import design as D

EV = D.EVIDENCE
AN = os.path.join(D.ROOT, 'analysis')


def load(path):
    return json.load(open(path)) if os.path.exists(path) else None


def main():
    v = load(os.path.join(EV, 'verification.json'))
    t = load(os.path.join(EV, 'terrain_check.json'))
    a = load(os.path.join(EV, 'arm_pose_crosscheck.json'))
    d = load(os.path.join(AN, 'drive_sizing.json'))
    g = load(os.path.join(AN, 'gripper_gap.json'))
    L = ['# Verification report — Thenar Walker', '',
         'Generated by `cad/tools/make_report.py` from `cad/evidence/*.json` (SolidWorks 2026 SP4.1 API runs) '
         'and `analysis/*.json`. Re-run the tools to refresh; do not edit by hand.', '']
    if v:
        L += ['## RoboReach rule checks (SolidWorks, exact B-rep)', '', '| Result | Check | Measured |', '|---|---|---|']
        for c in v['checks']:
            det = re.sub(r'np\.float64\(([^)]*)\)', lambda mm: mm.group(1), c['detail']).replace('|', '/')
            L.append(f"| {'PASS' if c['pass'] else '**FAIL**'} | {c['check']} | {det} |")
        L += ['', 'How each number is measured:', '',
              '* **Start box** — exact extreme points of every solid body (`IBody2.GetExtremePoint`) in the STOW configuration.',
              '* **Ground clearance** — lowest extreme point of every component except hubs/tyres.',
              '* **Grasp centre** — URDF forward kinematics of the `gripper_frame_link`; the SolidWorks arm matches the URDF '
              'to 0.04 mm in every pose (table below).',
              '* **Interference** — SolidWorks Interference Detection through all sub-assembly levels. The six '
              'servo-spline/horn overlaps (9.0 mm³ each) are how the thenar-arms CAD models the horn press-fit and are listed, not failed.',
              '* **Stability** — centre of gravity from SolidWorks volumes/centroids × datasheet masses (printed parts at '
              f'{D.PETG_G_CC} g/cm³ × {D.PRINT_FILL} fill), projected onto the wheel-contact rectangle, flat and on a 15° ramp.', '']
        L += ['### Per configuration', '', '| Config | Joint angles (deg) | Size L×W×H (mm) | Lowest non-wheel z | Mass | COG (mm) | Grasp centre (mm) |',
              '|---|---|---|---|---|---|---|']
        for n, c in v['configs'].items():
            L.append(f"| {n} | {c['joint_deg']} | {' × '.join(str(x) for x in c['size_lwh_mm'])} | {c['lowest_non_wheel']['z_mm']} | "
                     f"{c['mass_total_g']:.0f} g | {c['cog_mm']} | {c['grasp_centre_mm']} |")
        L.append('')
    if a:
        L += ['## Arm: SolidWorks vs URDF forward kinematics', '', '| Pose | max bounding-box difference (mm) |', '|---|---|']
        for n, e in a.get('reopen_check', {}).items():
            L.append(f'| {n} | {e} |')
        L.append('')
    if t:
        L += ['## Obstacles: robot on the arena ramp, bridge and speed breakers (SolidWorks)', '',
              'Robot pose solved so both axles\' tyres rest tangent on the real profile (`cad/tools/terrain.py`), then '
              'SolidWorks interference between every robot component and the arena board.', '',
              '| Case | Pitch (deg) | Chassis/motor/arm hits | Tyre contact overlaps | Result |', '|---|---|---|---|---|']
        for n, c in t.items():
            if n.startswith('_'):
                continue
            mx = max([i['volume_mm3'] for i in c['tyre_contact_overlaps']], default=0)
            L.append(f"| {n} | {c['pitch_deg']} | {len(c['chassis_terrain_interference'])} | {len(c['tyre_contact_overlaps'])} (max {mx} mm³) | "
                     f"{'PASS' if c['pass'] else '**FAIL**'} |")
        L.append('')
    if d:
        L += ['## Drive and power sizing (`analysis/drive_sizing.py`)', '', '| Quantity | Value |', '|---|---|']
        for k, val in d.items():
            L.append(f'| {k} | {val} |')
        L.append('')
    if g:
        L += ['## Gripper opening (`analysis/gripper_gap.py`, URDF meshes)', '',
              '| Gripper joint (deg) | Inner gap 15 mm behind the tips (mm) |', '|---|---|']
        for k, val in g.items():
            L.append(f"| {k} | {val['inner_gap_15mm_from_tip']} |")
        L.append('')
    L += ['## Not verified (needs the real robot)', '',
          '* Real part dimensions (motor shaft length, board sizes, servo spline) — the CAD uses nominal envelopes.',
          '* Print strength, tyre grip on the actual arena surface, dynamic tipping under hard braking.',
          '* Servo calibration and powered arm motion (thenar-arms R3 is itself not yet physically validated).',
          '* Radio range/latency in a crowded venue; firmware is compiled and unit-tested on the host, not run on hardware.',
          '* Arena positions are reconstructed from the rulebook renders (the rulebook allows ~10 % differences).']
    out = os.path.join(D.ROOT, 'docs', 'VERIFICATION.md')
    open(out, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print('wrote', out)


if __name__ == '__main__':
    main()
