"""Create firmware/libraries/ThenarLink/src/team_config.h with a fresh random link key.

  python firmware/tools/new_key.py "Your Team Name" "your-wifi-password"

The file is git-ignored. Flash BOTH ESP32s (robot and controller) after generating it —
they must share the same key. Never commit it or post it.
"""
import os
import secrets
import sys

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, '..', 'libraries', 'ThenarLink', 'src', 'team_config.h')
team = sys.argv[1] if len(sys.argv) > 1 else input('Team name: ')
pw = sys.argv[2] if len(sys.argv) > 2 else secrets.token_urlsafe(12)
if not 8 <= len(pw) <= 63:
    sys.exit('WPA2 password must be 8..63 characters')
key = secrets.token_bytes(32)
rows = ',\n    '.join(', '.join(f'0x{b:02x}' for b in key[i:i + 16]) for i in (0, 16))
team_c = team.replace('\\', '\\\\').replace('"', '\\"')
pw_c = pw.replace('\\', '\\\\').replace('"', '\\"')
with open(out, 'w', encoding='utf-8') as f:
    f.write(f'''// Generated by firmware/tools/new_key.py — SECRET, git-ignored. Same file on robot + controller.
#pragma once
#include <stdint.h>
namespace team {{
constexpr const char *TEAM_NAME = "{team_c}";
constexpr const char *WIFI_PASSWORD = "{pw_c}";
constexpr uint8_t LINK_KEY[32] = {{
    {rows}}};
}}  // namespace team
''')
ssid = ''.join(team.split())[:20] + '_TF'
print(f'wrote {os.path.normpath(out)}\nSSID will be: {ssid}\nWi-Fi password: {pw}')
